apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: <namespace>
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
    - port: 443
      targetPort: 443
      protocol: TCP
      name: websecure
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: custom-port

